#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)
#ifndef GAMEOVERSEASSDK_SWIFT_H
#define GAMEOVERSEASSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="GameOverseasSdk",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class QHADRewardVideo;

SWIFT_PROTOCOL("_TtP15GameOverseasSdk19ADRewardVideoDelete_")
@protocol ADRewardVideoDelete
/// 广告达到激励条件
- (void)adRewardVideoDidRewardEffectiveWithRewarded:(QHADRewardVideo * _Nonnull)rewarded;
/// 视频广告获取失败
/// note:
/// - 广告失败不会重试,请开发者轮换下一个广告!
- (void)adRewardVideoWithRewarded:(QHADRewardVideo * _Nonnull)rewarded error:(NSError * _Nonnull)error;
@end



/// 参数key
SWIFT_CLASS("_TtC15GameOverseasSdk11QGOSSConfig")
@interface QGOSSConfig : NSObject
/// 应用 key
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull appkey;)
+ (NSString * _Nonnull)appkey SWIFT_WARN_UNUSED_RESULT;
/// 打点 sdk key
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull qdasKey;)
+ (NSString * _Nonnull)qdasKey SWIFT_WARN_UNUSED_RESULT;
/// faceBookKey
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull faceBookKey;)
+ (NSString * _Nonnull)faceBookKey SWIFT_WARN_UNUSED_RESULT;
/// googleKey
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull googleKey;)
+ (NSString * _Nonnull)googleKey SWIFT_WARN_UNUSED_RESULT;
/// googleServerKey
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull googleServerKey;)
+ (NSString * _Nonnull)googleServerKey SWIFT_WARN_UNUSED_RESULT;
/// lineKey
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull lineKey;)
+ (NSString * _Nonnull)lineKey SWIFT_WARN_UNUSED_RESULT;
/// twitterKey
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull twitterKey;)
+ (NSString * _Nonnull)twitterKey SWIFT_WARN_UNUSED_RESULT;
/// twitterSecret
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull twitterSecret;)
+ (NSString * _Nonnull)twitterSecret SWIFT_WARN_UNUSED_RESULT;
/// twitterCallbackUrl
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull twitterCallbackUrl;)
+ (NSString * _Nonnull)twitterCallbackUrl SWIFT_WARN_UNUSED_RESULT;
/// 广告 key
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull adKey;)
+ (NSString * _Nonnull)adKey SWIFT_WARN_UNUSED_RESULT;
/// 广告 spaceId
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull adSpaceId;)
+ (NSString * _Nonnull)adSpaceId SWIFT_WARN_UNUSED_RESULT;
/// 是不是使用测试广告
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull isAdTest;)
+ (NSString * _Nonnull)isAdTest SWIFT_WARN_UNUSED_RESULT;
/// 是不是开启地理位置获取
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull enableLocation;)
+ (NSString * _Nonnull)enableLocation SWIFT_WARN_UNUSED_RESULT;
/// 广告统计key
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull flyerKey;)
+ (NSString * _Nonnull)flyerKey SWIFT_WARN_UNUSED_RESULT;
/// appleId(苹果开发者创建的应用的id)
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull appleId;)
+ (NSString * _Nonnull)appleId SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIApplication;

/// Game SDK for Overseas
SWIFT_CLASS("_TtC15GameOverseasSdk13QGOSSdkMatrix")
@interface QGOSSdkMatrix : NSObject
/// 单例方法
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) QGOSSdkMatrix * _Nonnull shared;)
+ (QGOSSdkMatrix * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// 初始化SDK
/// \param application UIApplication
///
/// \param launchOptions Options
///
/// \param parameters 初始化所需参数字典
///
+ (void)registerSDK:(UIApplication * _Nonnull)application launchOptions:(NSDictionary<UIApplicationLaunchOptionsKey, id> * _Nullable)launchOptions parameters:(NSDictionary<NSString *, id> * _Nonnull)parameters;
/// 设置应用支持方向接口
/// note:
/// 默认横屏（UIInterfaceOrientationMask.landscape）
/// note:
/// 此方法必须接入，否则可能导致 SDK 页面展示异常
@property (nonatomic) UIInterfaceOrientationMask supportInterfaceOriention;
/// 获取当前sdk版本号
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkVersion;)
+ (NSString * _Nonnull)sdkVersion SWIFT_WARN_UNUSED_RESULT;
/// 是否开启日志
/// note:
/// 默认false，需要在SDK初始化之前调用
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL isLogEnable;)
+ (BOOL)isLogEnable SWIFT_WARN_UNUSED_RESULT;
+ (void)setIsLogEnable:(BOOL)newValue;
/// SDK回调
/// \param application UIApplication
///
/// \param open url URL
///
/// \param options 参数字典
///
+ (BOOL)handleOpenURL:(UIApplication * _Nonnull)app open:(NSURL * _Nonnull)url options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> * _Nonnull)options SWIFT_WARN_UNUSED_RESULT;
/// 登录方法
/// \param onSignIn 登录回调
///
/// \param onBindingAccount 绑定回调
///
+ (void)loginOnSignIn:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nonnull))onSignIn onBindingAccount:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nonnull))onBindingAccount;
/// 切换账号
/// \param onSignIn 登录回调
///
/// \param onBindingAccount 绑定回调
///
+ (void)changeAccountOnSignIn:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nonnull))onSignIn onBindingAccount:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nonnull))onBindingAccount;
/// 退出登录
/// \param callbock 退出登录回调
///
+ (void)loginOutWithCallbock:(void (^ _Nonnull)(void))callbock;
/// 游客账号升级为正式账号
/// \param isBindingAccountSuccess 绑定是不是成功
///
+ (void)setBindingAccountResultWithIsBindingAccountSuccess:(BOOL)isBindingAccountSuccess;
/// 加载广告
/// <ul>
///   <li>
///     Parameters
///   </li>
///   <li>
///     onAdShow:        展示回调
///   </li>
///   <li>
///     onReward:        达到激励条件回调
///   </li>
///   <li>
///     onAdClick:       点击回调
///   </li>
///   <li>
///     onAdClose:       关闭回调
///   </li>
///   <li>
///     onRenderFailed:  广告加载失败回调
///   </li>
/// </ul>
+ (void)loadAdOnAdShow:(void (^ _Nonnull)(void))onAdShow onReward:(void (^ _Nonnull)(void))onReward onAdClick:(void (^ _Nonnull)(void))onAdClick onAdClose:(void (^ _Nonnull)(void))onAdClose onRenderFailed:(void (^ _Nonnull)(NSError * _Nonnull))onRenderFailed;
/// 发起支付
/// <ul>
///   <li>
///     Parameters
///   </li>
///   <li>
///     appUserId:          调用方用户id
///   </li>
///   <li>
///     appUserName:        调用方用户名称
///   </li>
///   <li>
///     productId:          产品id（联系运营核实）
///   </li>
///   <li>
///     productName:        产品名字
///   </li>
///   <li>
///     productAmount:      金额（单位分）
///   </li>
///   <li>
///     notiUrl:            发货通知地址
///   </li>
///   <li>
///     ipaProductIdentify: 开发者中心的商品id
///   </li>
///   <li>
///     onPaySuccess:  成功回调
///   </li>
///   <li>
///     onPayFailure:  失败回调
///   </li>
/// </ul>
+ (void)payWithAppUserId:(NSString * _Nonnull)appUserId appUserName:(NSString * _Nonnull)appUserName productId:(NSString * _Nonnull)productId productName:(NSString * _Nonnull)productName productAmount:(NSString * _Nonnull)productAmount notiUrl:(NSString * _Nonnull)notiUrl ipaProductIdentify:(NSString * _Nonnull)ipaProductIdentify onPaySuccess:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nonnull))onPaySuccess onPayFailure:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nonnull))onPayFailure;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIEvent;

@interface UIButton (SWIFT_EXTENSION(GameOverseasSdk))
- (BOOL)pointInside:(CGPoint)point withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
@end





#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
// Generated by Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)
#ifndef GAMEOVERSEASSDK_SWIFT_H
#define GAMEOVERSEASSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="GameOverseasSdk",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class QHADRewardVideo;

SWIFT_PROTOCOL("_TtP15GameOverseasSdk19ADRewardVideoDelete_")
@protocol ADRewardVideoDelete
/// 广告达到激励条件
- (void)adRewardVideoDidRewardEffectiveWithRewarded:(QHADRewardVideo * _Nonnull)rewarded;
/// 视频广告获取失败
/// note:
/// - 广告失败不会重试,请开发者轮换下一个广告!
- (void)adRewardVideoWithRewarded:(QHADRewardVideo * _Nonnull)rewarded error:(NSError * _Nonnull)error;
@end



/// 参数key
SWIFT_CLASS("_TtC15GameOverseasSdk11QGOSSConfig")
@interface QGOSSConfig : NSObject
/// 应用 key
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull appkey;)
+ (NSString * _Nonnull)appkey SWIFT_WARN_UNUSED_RESULT;
/// 打点 sdk key
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull qdasKey;)
+ (NSString * _Nonnull)qdasKey SWIFT_WARN_UNUSED_RESULT;
/// faceBookKey
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull faceBookKey;)
+ (NSString * _Nonnull)faceBookKey SWIFT_WARN_UNUSED_RESULT;
/// googleKey
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull googleKey;)
+ (NSString * _Nonnull)googleKey SWIFT_WARN_UNUSED_RESULT;
/// googleServerKey
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull googleServerKey;)
+ (NSString * _Nonnull)googleServerKey SWIFT_WARN_UNUSED_RESULT;
/// lineKey
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull lineKey;)
+ (NSString * _Nonnull)lineKey SWIFT_WARN_UNUSED_RESULT;
/// twitterKey
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull twitterKey;)
+ (NSString * _Nonnull)twitterKey SWIFT_WARN_UNUSED_RESULT;
/// twitterSecret
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull twitterSecret;)
+ (NSString * _Nonnull)twitterSecret SWIFT_WARN_UNUSED_RESULT;
/// twitterCallbackUrl
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull twitterCallbackUrl;)
+ (NSString * _Nonnull)twitterCallbackUrl SWIFT_WARN_UNUSED_RESULT;
/// 广告 key
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull adKey;)
+ (NSString * _Nonnull)adKey SWIFT_WARN_UNUSED_RESULT;
/// 广告 spaceId
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull adSpaceId;)
+ (NSString * _Nonnull)adSpaceId SWIFT_WARN_UNUSED_RESULT;
/// 是不是使用测试广告
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull isAdTest;)
+ (NSString * _Nonnull)isAdTest SWIFT_WARN_UNUSED_RESULT;
/// 是不是开启地理位置获取
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull enableLocation;)
+ (NSString * _Nonnull)enableLocation SWIFT_WARN_UNUSED_RESULT;
/// 广告统计key
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull flyerKey;)
+ (NSString * _Nonnull)flyerKey SWIFT_WARN_UNUSED_RESULT;
/// appleId(苹果开发者创建的应用的id)
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull appleId;)
+ (NSString * _Nonnull)appleId SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIApplication;

/// Game SDK for Overseas
SWIFT_CLASS("_TtC15GameOverseasSdk13QGOSSdkMatrix")
@interface QGOSSdkMatrix : NSObject
/// 单例方法
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) QGOSSdkMatrix * _Nonnull shared;)
+ (QGOSSdkMatrix * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// 初始化SDK
/// \param application UIApplication
///
/// \param launchOptions Options
///
/// \param parameters 初始化所需参数字典
///
+ (void)registerSDK:(UIApplication * _Nonnull)application launchOptions:(NSDictionary<UIApplicationLaunchOptionsKey, id> * _Nullable)launchOptions parameters:(NSDictionary<NSString *, id> * _Nonnull)parameters;
/// 设置应用支持方向接口
/// note:
/// 默认横屏（UIInterfaceOrientationMask.landscape）
/// note:
/// 此方法必须接入，否则可能导致 SDK 页面展示异常
@property (nonatomic) UIInterfaceOrientationMask supportInterfaceOriention;
/// 获取当前sdk版本号
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkVersion;)
+ (NSString * _Nonnull)sdkVersion SWIFT_WARN_UNUSED_RESULT;
/// 是否开启日志
/// note:
/// 默认false，需要在SDK初始化之前调用
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL isLogEnable;)
+ (BOOL)isLogEnable SWIFT_WARN_UNUSED_RESULT;
+ (void)setIsLogEnable:(BOOL)newValue;
/// SDK回调
/// \param application UIApplication
///
/// \param open url URL
///
/// \param options 参数字典
///
+ (BOOL)handleOpenURL:(UIApplication * _Nonnull)app open:(NSURL * _Nonnull)url options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> * _Nonnull)options SWIFT_WARN_UNUSED_RESULT;
/// 登录方法
/// \param onSignIn 登录回调
///
/// \param onBindingAccount 绑定回调
///
+ (void)loginOnSignIn:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nonnull))onSignIn onBindingAccount:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nonnull))onBindingAccount;
/// 切换账号
/// \param onSignIn 登录回调
///
/// \param onBindingAccount 绑定回调
///
+ (void)changeAccountOnSignIn:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nonnull))onSignIn onBindingAccount:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nonnull))onBindingAccount;
/// 退出登录
/// \param callbock 退出登录回调
///
+ (void)loginOutWithCallbock:(void (^ _Nonnull)(void))callbock;
/// 游客账号升级为正式账号
/// \param isBindingAccountSuccess 绑定是不是成功
///
+ (void)setBindingAccountResultWithIsBindingAccountSuccess:(BOOL)isBindingAccountSuccess;
/// 加载广告
/// <ul>
///   <li>
///     Parameters
///   </li>
///   <li>
///     onAdShow:        展示回调
///   </li>
///   <li>
///     onReward:        达到激励条件回调
///   </li>
///   <li>
///     onAdClick:       点击回调
///   </li>
///   <li>
///     onAdClose:       关闭回调
///   </li>
///   <li>
///     onRenderFailed:  广告加载失败回调
///   </li>
/// </ul>
+ (void)loadAdOnAdShow:(void (^ _Nonnull)(void))onAdShow onReward:(void (^ _Nonnull)(void))onReward onAdClick:(void (^ _Nonnull)(void))onAdClick onAdClose:(void (^ _Nonnull)(void))onAdClose onRenderFailed:(void (^ _Nonnull)(NSError * _Nonnull))onRenderFailed;
/// 发起支付
/// <ul>
///   <li>
///     Parameters
///   </li>
///   <li>
///     appUserId:          调用方用户id
///   </li>
///   <li>
///     appUserName:        调用方用户名称
///   </li>
///   <li>
///     productId:          产品id（联系运营核实）
///   </li>
///   <li>
///     productName:        产品名字
///   </li>
///   <li>
///     productAmount:      金额（单位分）
///   </li>
///   <li>
///     notiUrl:            发货通知地址
///   </li>
///   <li>
///     ipaProductIdentify: 开发者中心的商品id
///   </li>
///   <li>
///     onPaySuccess:  成功回调
///   </li>
///   <li>
///     onPayFailure:  失败回调
///   </li>
/// </ul>
+ (void)payWithAppUserId:(NSString * _Nonnull)appUserId appUserName:(NSString * _Nonnull)appUserName productId:(NSString * _Nonnull)productId productName:(NSString * _Nonnull)productName productAmount:(NSString * _Nonnull)productAmount notiUrl:(NSString * _Nonnull)notiUrl ipaProductIdentify:(NSString * _Nonnull)ipaProductIdentify onPaySuccess:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nonnull))onPaySuccess onPayFailure:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nonnull))onPayFailure;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIEvent;

@interface UIButton (SWIFT_EXTENSION(GameOverseasSdk))
- (BOOL)pointInside:(CGPoint)point withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
@end





#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#endif
